import click
import cli.config
import snakemake
import os

def read_samples_from_file(sample_file):

    with open(sample_file) as f:

        return f.readlines()

@click.group()
def main():
    pass

@main.command(help='Create a config YAML file for running the Snakemake pipeline.')
@click.option('--use-sample-files', is_flag=True, default=False, help='Load sample names from text files instead of passing them as a comma-seperated list.')
@click.option('--genome_build', type=click.Choice(['hg19','hg38']), default='hg38', help='Build of the reference used for annotation.')
@click.argument('fastq_dir')
@click.argument('reference_fasta')
@click.argument('group1')
@click.argument('group2')
@click.argument('output_dir')
@click.argument('target_yaml')
def create_config(use_sample_files, genome_build, fastq_dir, reference_fasta, group1, group2, output_dir, target_yaml):

    if (use_sample_files):

        samples_in_group1 = read_samples_from_file(group1)
        samples_in_group2 = read_samples_from_file(group2)

    else:

        samples_in_group1 = group1.split(',')
        samples_in_group2 = group2.split(',')

    config_yaml = cli.config.get_default_config(fastq_dir, reference_fasta, samples_in_group1, samples_in_group2, genome_build, output_dir)

    cli.config.dump_config(config_yaml, target_yaml)

@main.command(help='Run the snakemake pipeline using a config file')
@click.option('--dry-run', is_flag=True, default=False, help='Only dry-run the workflow.')
@click.option('--delete-all-output', is_flag=True, default=False, help='Remove all files generated by the workflow')
@click.argument('config_yaml')
def run_from_config(dry_run, delete_all_output, config_yaml):

    # get right directory, see https://stackoverflow.com/questions/4934806/how-can-i-find-scripts-directory-with-python
    script_dir = os.path.dirname(os.path.realpath(__file__))

    snakefile_location = script_dir + '/../snakemake/Snakefile'

    config_dir= os.path.dirname(os.path.realpath(config_yaml))

    snakemake.snakemake(
        snakefile=snakefile_location,
        configfile=config_yaml,
        workdir=config_dir,
        dryrun=dry_run,
        printshellcmds=True,
        delete_all_output=delete_all_output
    )
